// Generated by gencpp from file test/ControlState.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_CONTROLSTATE_H
#define TEST_MESSAGE_CONTROLSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct ControlState_
{
  typedef ControlState_<ContainerAllocator> Type;

  ControlState_()
    : axes()
    , buttons()
    , hat()  {
    }
  ControlState_(const ContainerAllocator& _alloc)
    : axes(_alloc)
    , buttons(_alloc)
    , hat(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _axes_type;
  _axes_type axes;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _buttons_type;
  _buttons_type buttons;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _hat_type;
  _hat_type hat;





  typedef boost::shared_ptr< ::test::ControlState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::ControlState_<ContainerAllocator> const> ConstPtr;

}; // struct ControlState_

typedef ::test::ControlState_<std::allocator<void> > ControlState;

typedef boost::shared_ptr< ::test::ControlState > ControlStatePtr;
typedef boost::shared_ptr< ::test::ControlState const> ControlStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::ControlState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::ControlState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test::ControlState_<ContainerAllocator1> & lhs, const ::test::ControlState_<ContainerAllocator2> & rhs)
{
  return lhs.axes == rhs.axes &&
    lhs.buttons == rhs.buttons &&
    lhs.hat == rhs.hat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test::ControlState_<ContainerAllocator1> & lhs, const ::test::ControlState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test::ControlState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::ControlState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::ControlState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::ControlState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::ControlState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::ControlState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::ControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1462100952344a6d9062ee185d9220e3";
  }

  static const char* value(const ::test::ControlState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1462100952344a6dULL;
  static const uint64_t static_value2 = 0x9062ee185d9220e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::ControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/ControlState";
  }

  static const char* value(const ::test::ControlState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::ControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] axes\n"
"int32[] buttons\n"
"int32[] hat\n"
;
  }

  static const char* value(const ::test::ControlState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::ControlState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axes);
      stream.next(m.buttons);
      stream.next(m.hat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::ControlState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::ControlState_<ContainerAllocator>& v)
  {
    s << indent << "axes[]" << std::endl;
    for (size_t i = 0; i < v.axes.size(); ++i)
    {
      s << indent << "  axes[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.axes[i]);
    }
    s << indent << "buttons[]" << std::endl;
    for (size_t i = 0; i < v.buttons.size(); ++i)
    {
      s << indent << "  buttons[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.buttons[i]);
    }
    s << indent << "hat[]" << std::endl;
    for (size_t i = 0; i < v.hat.size(); ++i)
    {
      s << indent << "  hat[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.hat[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_CONTROLSTATE_H
